export type Language = 'zh-CN' | 'en' | 'ko';

export const detectLanguage = (text: string): Language => {
  // Check for Chinese characters
  if (/[\u4e00-\u9fa5]/.test(text)) {
    return 'zh-CN';
  }
  
  // Check for Korean characters
  if (/[\uac00-\ud7af]|[\u1100-\u11ff]|[\u3130-\u318f]|[\ua960-\ua97f]|[\ud7b0-\ud7ff]/.test(text)) {
    return 'ko';
  }
  
  // Default to English
  return 'en';
};

export const getTranslation = (lang: Language, key: string): string => {
  const translations: Record<Language, Record<string, string>> = {
    'zh-CN': {
      appTitle: '雷诺曼读牌助手',
      appSubtitle: '让卡牌为你揭示未来的路径',
      questionPlaceholder: '输入你的问题...',
      startReading: '开始解读',
      selectCards: '选择卡牌',
      selected: '已选',
      reset: '重置',
      getReading: '获取解读',
      reading: '解读中...',
      overview: '概述',
      cardAnalysis: '逐卡解析',
      combinations: '组合洞见',
      advice: '可执行建议',
      love: '爱情',
      career: '职业',
      money: '金钱',
      family: '家庭',
      health: '健康',
      disclaimer: '注意：此解读仅供参考，不能替代专业建议。',
      exportJSON: '导出 JSON',
      copyText: '复制文本',
      shareReading: '分享解读',
      past: '过去',
      present: '当下',
      future: '未来',
      confidence: '置信度',
      manualSelect: '手动选择卡牌',
      cameraCapture: '使用相机识别',
      camera: '摄像头',
      retry: '重试',
      reading_rules: '雷诺曼占卜规则',
      rule_1: '雷诺曼不可以问是否问题。',
      rule_2: '雷诺曼最好不要问太久以后的问题，最近几个月的是最好最准的。',
      rule_3: '每次问题抽3张牌，把牌混合之后抽，心中默念问题，按着抽的顺序点击相对应的牌，进行解读。',
      rule_4: '所有的东西只是给一个方向性的预测，不论结局好坏请继续努力生活工作认真学习。',
      rule_5: '如果因为结果是好的而不继续做你该做的事情不会如愿。',
      rule_6: '如果结局不好但是付出努力改变会有一定的效果。',
      rule_7: '尽人事听天命。',
    },
    'en': {
      appTitle: 'Lenormand Reading Assistant',
      appSubtitle: 'Let the cards reveal your path forward',
      questionPlaceholder: 'Enter your question...',
      startReading: 'Start Reading',
      selectCards: 'Select Cards',
      selected: 'Selected',
      reset: 'Reset',
      getReading: 'Get Reading',
      reading: 'Reading...',
      overview: 'Overview',
      cardAnalysis: 'Card Analysis',
      combinations: 'Combination Insights',
      advice: 'Actionable Advice',
      love: 'Love',
      career: 'Career',
      money: 'Money',
      family: 'Family',
      health: 'Health',
      disclaimer: 'Note: This reading is for reference only and does not replace professional advice.',
      exportJSON: 'Export JSON',
      copyText: 'Copy Text',
      shareReading: 'Share Reading',
      past: 'Past',
      present: 'Present',
      future: 'Future',
      confidence: 'Confidence',
      manualSelect: 'Manual Card Selection',
      cameraCapture: 'Use Camera Recognition',
      camera: 'Camera',
      retry: 'Retry',
      reading_rules: 'Lenormand Reading Rules',
      rule_1: 'Lenormand cannot answer yes/no questions.',
      rule_2: 'Lenormand works best for near-future questions. The most accurate readings are for the next few months.',
      rule_3: 'Draw 3 cards for each question. Shuffle the cards, focus on your question, and click the cards in the order you drew them.',
      rule_4: 'All readings provide directional guidance. Regardless of the outcome, continue working hard and living your best life.',
      rule_5: 'If you stop working towards your goals because of a positive reading, you may not achieve the desired outcome.',
      rule_6: 'If the outcome seems negative, effort and change can still make a difference.',
      rule_7: 'Do your best and leave the rest to fate.',
    },
    'ko': {
      appTitle: '르노망 카드 리딩 도우미',
      appSubtitle: '카드가 당신의 앞길을 밝혀줍니다',
      questionPlaceholder: '질문을 입력하세요...',
      startReading: '리딩 시작',
      selectCards: '카드 선택',
      selected: '선택됨',
      reset: '재설정',
      getReading: '리딩 받기',
      reading: '리딩 중...',
      overview: '개요',
      cardAnalysis: '카드 분석',
      combinations: '조합 통찰',
      advice: '실행 가능한 조언',
      love: '사랑',
      career: '경력',
      money: '금전',
      family: '가족',
      health: '건강',
      disclaimer: '참고: 이 리딩은 참고용이며 전문적인 조언을 대체하지 않습니다.',
      exportJSON: 'JSON 내보내기',
      copyText: '텍스트 복사',
      shareReading: '리딩 공유',
      past: '과거',
      present: '현재',
      future: '미래',
      confidence: '신뢰도',
      manualSelect: '수동 카드 선택',
      cameraCapture: '카메라 인식 사용',
      camera: '카메라',
      retry: '다시 시도',
      reading_rules: '르노망 점술 규칙',
      rule_1: '르노망은 예/아니오 질문에 답할 수 없습니다.',
      rule_2: '르노망은 가까운 미래 질문에 가장 적합합니다. 가장 정확한 리딩은 향후 몇 개월입니다.',
      rule_3: '각 질문마다 3장의 카드를 뽑습니다. 카드를 섞고 질문에 집중한 후, 뽑은 순서대로 카드를 클릭하세요.',
      rule_4: '모든 리딩은 방향성 안내를 제공합니다. 결과와 관계없이 최선을 다해 노력하고 생활하세요.',
      rule_5: '긍정적인 리딩 때문에 목표를 향한 노력을 멈추면 원하는 결과를 얻지 못할 수 있습니다.',
      rule_6: '결과가 부정적으로 보이더라도 노력과 변화는 여전히 차이를 만들 수 있습니다.',
      rule_7: '최선을 다하고 나머지는 운명에 맡기세요.',
    },
  };
  
  return translations[lang][key] || key;
};
